### ISSUE TITLE
Erro ao cadastrar curso

### ISSUE THREAD

**Issue by Vitormdias** [FatecSorocaba/callforpapersXXIV#16]
![image](https://user-images.githubusercontent.com/18128585/30144427-8814837a-9361-11e7-9ee6-3c69de01746c.png)

No momento que cliquei em submeter proposta, fui redirecionado para /speakers e apareceu essa mensagem, além disso não recebi um e-mail

**Comment by CaiqueMitsuoka** [comment]
Sua talk foi submetida, mas o serviço de email falhou. Ja encontrei o log. Estamos resolvendo.
